import { DashboardData } from './types';

export const MOCK_DASHBOARD_DATA: DashboardData = {
  lastRefreshed: new Date().toISOString(),
  kpis: {
    todaySalesCents: 4825000, // LKR 48,250.00
    todayInvoicesCount: 18,
    avgBasketCents: 268000, // LKR 2,680.00
    activeRepairsCount: 12,
    readyRepairsCount: 5,
    uncollectedReadyValueCents: 2450000, // LKR 24,500.00
    activePrintJobsCount: 4,
    cashDrawerBalanceCents: 3240000, // LKR 32,400.00
    openingFloatCents: 1000000, // LKR 10,000.00
    cashSalesCents: 2240000,
    cardSalesCents: 1560000,
    onlineSalesCents: 725000,
    creditSalesCents: 300000,
  },
  urgentActions: [
    {
      id: 'urg-1',
      type: 'stockout',
      title: 'iPhone 20W USB-C Power Adapter is OUT OF STOCK',
      subtitle: '0 units remaining on shelf · 6 units sold yesterday',
      severity: 'critical',
      timestamp: '10 mins ago',
      referenceId: 'prod_pwr_20w',
      actionLabel: 'Restock Stock',
      linkTo: '/inventory',
    },
    {
      id: 'urg-2',
      type: 'pending_approval',
      title: 'Estimate Approval: Samsung S22 Ultra Display Replacement',
      subtitle: 'Quotation: Rs. 38,500.00 · Customer waiting for phone callback',
      severity: 'warning',
      timestamp: '35 mins ago',
      referenceId: 'TKT-1092',
      customerName: 'Dinesh Kumara',
      customerPhone: '0771234567',
      amountCents: 3850000,
      actionLabel: 'Call Customer',
      linkTo: '/repairs',
    },
    {
      id: 'urg-3',
      type: 'overdue_repair',
      title: 'Promised Deadline Exceeded: Redmi Note 11 Battery Change',
      subtitle: 'Promised by 10:00 AM · Assigned to Kamal Gunaratne',
      severity: 'critical',
      timestamp: '1 hour overdue',
      referenceId: 'TKT-1088',
      customerName: 'Nirosha Perera',
      customerPhone: '0719876543',
      actionLabel: 'View Ticket',
      linkTo: '/repairs',
    },
    {
      id: 'urg-4',
      type: 'uncollected',
      title: 'Uncollected Device: iPad 9th Gen Glass Replacement Ready for 4 Days',
      subtitle: 'Balance Due: Rs. 14,000.00 · Completed by Nuwan',
      severity: 'warning',
      timestamp: '4 days ready',
      referenceId: 'TKT-1045',
      customerName: 'Saman Jayakody',
      customerPhone: '0785551234',
      amountCents: 1400000,
      daysWaiting: 4,
      actionLabel: 'Send Reminder',
      linkTo: '/repairs',
    },
    {
      id: 'urg-5',
      type: 'credit_overdue',
      title: 'Credit Payment Overdue: Kandy Tech Solutions',
      subtitle: 'Overdue installment of Rs. 18,500.00 · Due date was yesterday',
      severity: 'warning',
      timestamp: '1 day overdue',
      referenceId: 'INV-2041',
      customerName: 'Kandy Tech Solutions',
      customerPhone: '0812233445',
      amountCents: 1850000,
      actionLabel: 'Record Payment',
      linkTo: '/invoices',
    },
  ],
  repairPipeline: [
    { stage: 'received', label: 'Received', count: 3, color: 'blue', percentage: 25 },
    { stage: 'diagnosing', label: 'Diagnosing', count: 2, color: 'yellow', percentage: 17 },
    {
      stage: 'pending_approval',
      label: 'Waiting Approval',
      count: 3,
      color: 'orange',
      percentage: 25,
    },
    { stage: 'in_repair', label: 'In Repair', count: 4, color: 'grape', percentage: 33 },
    { stage: 'ready', label: 'Ready for Pickup', count: 5, color: 'teal', percentage: 42 },
  ],
  printPipeline: [
    { stage: 'received', label: 'Queued', count: 2, color: 'blue', percentage: 25 },
    {
      stage: 'in_progress',
      label: 'Printing / Pressing',
      count: 2,
      color: 'orange',
      percentage: 25,
    },
    { stage: 'ready', label: 'Ready for Collection', count: 3, color: 'teal', percentage: 38 },
    { stage: 'delivered', label: 'Delivered Today', count: 5, color: 'green', percentage: 62 },
  ],
  technicians: [
    {
      employeeKey: 'emp_001',
      name: 'Kamal Gunaratne',
      role: 'Senior Hardware Tech',
      activeJobsCount: 4,
      completedTodayCount: 2,
      capacityPercentage: 85,
      currentTask: 'iPhone 13 IC Reballing (TKT-1090)',
      status: 'busy',
    },
    {
      employeeKey: 'emp_002',
      name: 'Nimal Jayasuriya',
      role: 'Screen & Glass Specialist',
      activeJobsCount: 1,
      completedTodayCount: 4,
      capacityPercentage: 30,
      currentTask: 'Oppo Reno 8 Screen Replacement (TKT-1094)',
      status: 'available',
    },
    {
      employeeKey: 'emp_003',
      name: 'Sunil Weerasinghe',
      role: 'Print Machine Operator',
      activeJobsCount: 3,
      completedTodayCount: 5,
      capacityPercentage: 65,
      currentTask: 'Batch 50x Sublimation Mugs (PRN-0342)',
      status: 'busy',
    },
  ],
  fastMovingItems: [
    {
      productId: 'p-1',
      productKey: 'prod_tg_9d',
      name: 'Universal 9D Full Cover Tempered Glass',
      category: 'Screen Protectors',
      soldTodayUnits: 14,
      remainingStock: 22,
      sellingPriceCents: 45000, // Rs. 450.00
      minThreshold: 10,
    },
    {
      productId: 'p-2',
      productKey: 'prod_cab_typec',
      name: '65W Fast Charging Braided Type-C Cable 1m',
      category: 'Cables & Adapters',
      soldTodayUnits: 8,
      remainingStock: 5,
      sellingPriceCents: 85000, // Rs. 850.00
      minThreshold: 8,
    },
    {
      productId: 'p-3',
      productKey: 'prod_mug_blank',
      name: 'White Ceramic 11oz Sublimation Mug Blank',
      category: 'Print Supplies',
      soldTodayUnits: 50,
      remainingStock: 35,
      sellingPriceCents: 35000, // Rs. 350.00
      minThreshold: 25,
    },
    {
      productId: 'p-4',
      productKey: 'prod_pouch_clear',
      name: 'Shockproof Clear Case for iPhone 14/15',
      category: 'Protective Cases',
      soldTodayUnits: 6,
      remainingStock: 12,
      sellingPriceCents: 75000, // Rs. 750.00
      minThreshold: 5,
    },
  ],
  recentActivities: [
    {
      id: 'act-1',
      type: 'sale',
      title: 'Sale Completed · INV-1048',
      description: 'Rs. 3,450.00 (Cash) · 3 retail items · Cashier: Sandun',
      amountCents: 345000,
      timeAgo: '3 mins ago',
      icon: 'IconReceipt',
      color: 'blue',
      linkTo: '/invoices',
    },
    {
      id: 'act-2',
      type: 'repair_update',
      title: 'Repair Ready for Pickup · TKT-1087',
      description: 'Vivo Y20 Screen Replacement completed by Nimal',
      amountCents: 850000,
      timeAgo: '12 mins ago',
      icon: 'IconHammer',
      color: 'teal',
      linkTo: '/repairs',
    },
    {
      id: 'act-3',
      type: 'print_new',
      title: 'New Print Job Registered · PRN-0344',
      description: '20 Custom T-Shirts (Black Cotton) for Apex Gym',
      amountCents: 2800000,
      timeAgo: '24 mins ago',
      icon: 'IconPrinter',
      color: 'orange',
      linkTo: '/print-jobs',
    },
    {
      id: 'act-4',
      type: 'credit_payment',
      title: 'Credit Installment Received',
      description: 'Rs. 10,000.00 paid by Lanka Motors towards INV-0992',
      amountCents: 1000000,
      timeAgo: '45 mins ago',
      icon: 'IconCoin',
      color: 'green',
      linkTo: '/invoices',
    },
    {
      id: 'act-5',
      type: 'stock_alert',
      title: 'Low Stock Reorder Threshold Reached',
      description: 'Type-C Fast Cable fell below 8 units (5 units remaining)',
      timeAgo: '1 hour ago',
      icon: 'IconAlertTriangle',
      color: 'red',
      linkTo: '/inventory',
    },
  ],
  shiftSummary: {
    openingFloatCents: 1000000, // Rs. 10,000.00
    cashSalesCents: 2240000, // Rs. 22,400.00
    cardSalesCents: 1560000, // Rs. 15,600.00
    onlineSalesCents: 725000, // Rs. 7,250.00
    creditSalesCents: 300000, // Rs. 3,000.00
    cashOutCents: 0,
    expectedDrawerCashCents: 3240000, // Rs. 32,400.00
  },
};
