// Generated by scripts/generate-icon-shards.mjs — do not edit by hand.
/** Shard key -> loader, keyed exactly as `shardKeyForIcon` in the generator computes it. */
export const ICON_SHARD_LOADERS: Record<string, () => Promise<Record<string, unknown>>> = {
  _: () => import('./_'),
  a: () => import('./a'),
  b: () => import('./b'),
  c: () => import('./c'),
  d: () => import('./d'),
  e: () => import('./e'),
  f: () => import('./f'),
  g: () => import('./g'),
  h: () => import('./h'),
  i: () => import('./i'),
  j: () => import('./j'),
  k: () => import('./k'),
  l: () => import('./l'),
  m: () => import('./m'),
  n: () => import('./n'),
  o: () => import('./o'),
  p: () => import('./p'),
  q: () => import('./q'),
  r: () => import('./r'),
  s: () => import('./s'),
  t: () => import('./t'),
  u: () => import('./u'),
  v: () => import('./v'),
  w: () => import('./w'),
  x: () => import('./x'),
  y: () => import('./y'),
  z: () => import('./z'),
};

export const ICON_SHARD_KEYS = Object.keys(ICON_SHARD_LOADERS);

/** The shard holding `name` (PascalCase, no `Icon` prefix), or null if it can't be in any shard. */
export function shardKeyForIconName(name: string): string | null {
  const first = name.slice(0, 1).toLowerCase();
  const key = first >= 'a' && first <= 'z' ? first : '_';
  return key in ICON_SHARD_LOADERS ? key : null;
}
