// Generated by scripts/generate-icon-shards.mjs — do not edit by hand.
export {
  IconJacket,
  IconJetpack,
  IconJetpackFilled,
  IconJetski,
  IconJewishStar,
  IconJewishStarFilled,
  IconJoinBevel,
  IconJoinRound,
  IconJoinStraight,
  IconJoker,
  IconJpg,
  IconJson,
  IconJumpRope,
} from '@tabler/icons-react';
