// Generated by scripts/generate-icon-shards.mjs — do not edit by hand.
export {
  IconQrcode,
  IconQrcodeOff,
  IconQuestionMark,
  IconQueuePopIn,
  IconQueuePopOut,
  IconQuote,
  IconQuoteFilled,
  IconQuoteOff,
  IconQuoteOpen,
  IconQuotes,
} from '@tabler/icons-react';
