// Generated by scripts/generate-icon-shards.mjs — do not edit by hand.
export {
  IconX,
  IconXFilled,
  IconXMark,
  IconXPowerY,
  IconXboxA,
  IconXboxAFilled,
  IconXboxB,
  IconXboxBFilled,
  IconXboxX,
  IconXboxXFilled,
  IconXboxY,
  IconXboxYFilled,
  IconXd,
  IconXxx,
} from '@tabler/icons-react';
